#[derive(Debug, Clone)]
pub enum DevicesAction {
    Refresh,
    RetryDeviceBootstrap,
    NodeCardClick(String),
    /// Pointer entered a node card (or re-entered after leaving another).
    SetNodeHover(Option<String>),
    /// Clear hover only if it still matches this node (safe when crossing cards).
    ClearNodeHoverIf(String),
    OpenNode(String),
    BackToGrid,
    OpenJoinModal,
    OpenCreateClusterModal,
    CreateCluster,
    CreateClusterNameEdit(crate::ui::text_field_input::TextFieldEditAction),
    FocusCreateClusterName,
    CloseCreateClusterModal,
    CloseJoinModal,
    PasteJoinInvite,
    SubmitJoin,
    CopyInvite,
    ToggleClusterPicker,
    CloseClusterPicker,
    SelectCluster(String),
    LeaveCluster,
    OpenDeleteClusterModal,
    CloseDeleteClusterModal,
    ConfirmDeleteCluster,
    ShareBack,
    ShareForward,
    ShareNavigate {
        volume_id: Option<String>,
        name: String,
    },
    OpenShareAddModal,
    CloseShareAddModal,
    BrowseShareAddPath,
    SubmitShareAdd,
    ToggleShareNewMenu,
    CloseShareNewMenu,
    ShareCreateFolder,
    ShareCreateTxt,
    ShareOpenFile(String),
    ShareSyncFile(String),
    ShareRemoteOpenFile(String),
    ShareRemoteOpenOnHost(String),
    ShareDeleteFile(String),
    OpenShareRenameModal(String),
    CloseShareRenameModal,
    ShareRenameEdit(crate::ui::text_field_input::TextFieldEditAction),
    FocusShareRenameField,
    ConfirmShareRename,
    OpenShareUnshareModal(String),
    CloseShareUnshareModal,
    ConfirmShareUnshare,
    OpenShareContextMenu {
        name: String,
        x: f32,
        y: f32,
    },
    CloseShareContextMenu,
    ShareFileClick(String),
    WorkspaceRefresh,
    OpenWorkspaceAppPicker,
    CloseWorkspaceAppPicker,
    SelectWorkspaceApp(String),
    WorkspaceAppSearchEdit(crate::ui::text_field_input::TextFieldEditAction),
    FocusWorkspaceAppSearch,
    DeviceSearchEdit(crate::ui::text_field_input::TextFieldEditAction),
    FocusDeviceSearch,
    BlurDeviceSearch,
    ConfirmWorkspaceAppOpen,
    WorkspaceInstallAndOpen(String),
    WorkspaceOpenSelected,
    WorkspaceRequestProvision,
    WorkspaceRetryProvision,
    WorkspaceApproveProvision(String),
    WorkspaceApproveProvisionCandidate {
        job_id: String,
        vm_name: String,
    },
    WorkspaceDismissApproval(String),
    OpenDeleteNodeModal(String),
    CloseDeleteNodeModal,
    ConfirmDeleteNode,
    OpenDeviceContextMenu {
        node_id: String,
        x: f32,
        y: f32,
    },
    CloseDeviceContextMenu,
    SendMessage(String),
    OpenRemoteDesktop(String),
}
