#[derive(Debug, Clone)]
pub enum DevicesAction {
    Refresh,
    RetryDeviceBootstrap,
    NodeCardClick(String),
    SetNodeHover(Option<String>),
    OpenNode(String),
    BackToGrid,
    OpenJoinModal,
    CloseJoinModal,
    PasteJoinInvite,
    SubmitJoin,
    CopyInvite,
    ToggleClusterPicker,
    CloseClusterPicker,
    SelectCluster(String),
    ShareBack,
    ShareForward,
    ShareNavigate {
        volume_id: Option<String>,
        name: String,
    },
    OpenShareAddModal,
    CloseShareAddModal,
    BrowseShareAddPath,
    SubmitShareAdd,
    ShareOpenFile(String),
    ShareSyncFile(String),
    ShareRemoteOpenFile(String),
    ShareDeleteFile(String),
    OpenShareContextMenu {
        name: String,
        x: f32,
        y: f32,
    },
    CloseShareContextMenu,
    ShareFileClick(String),
    OpenDeleteNodeModal(String),
    CloseDeleteNodeModal,
    ConfirmDeleteNode,
    OpenDeviceContextMenu {
        node_id: String,
        x: f32,
        y: f32,
    },
    CloseDeviceContextMenu,
}
